### ISSUE TITLE
After running python main.py -m test -i demo, I have been stopping here waiting for download. How long does it take to download?

### ISSUE THREAD

**Issue by Kenny-Li2023** [FuxiCV/MeInGame#14]
![image](https://user-images.githubusercontent.com/48302836/110640152-77ac2480-81eb-11eb-8c34-431e479366f1.png)
After running python main.py -m test -i demo, I have been stopping here waiting for download. How long does it take to download?

**Comment by WANGEOGEO** [comment]
I think maybe you need to download this FAN on your own, and put it in the according directory for MeInGame to use.

**Comment by pyh007** [comment]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from uv_inpainting import UVInpainting
  File "/root/MeInGame/uv_inpainting.py", line 25, in <module>
    from lib.image_cropper import ImageCropper
  File "/root/MeInGame/lib/image_cropper.py", line 7, in <module>
    from lib import face_align
  File "/root/MeInGame/lib/face_align.py", line 9, in <module>
    from face_alignment.models import FAN, ResNetDepth
ModuleNotFoundError: No module named 'face_alignment.models'请问下执行的时候遇到这个问题什么原因
