### ISSUE TITLE
UserWarning: Faces have invalid indices

### ISSUE THREAD

**Issue by Laborant** [FuxiCV/MeInGame#15]
2021-03-11 14:36:42.069441: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
/home/b/anaconda3/envs/fit/lib/python3.7/site-packages/pytorch3d/io/obj_io.py:70: UserWarning: Faces have invalid indices
  warnings.warn("Faces have invalid indices")
Traceback (most recent call last):
  File "main.py", line 180, in <module>
    main()
  File "main.py", line 146, in main
    model = UVInpainting(config, device, sess, graph)
  File "/home/b/MeInGame/uv_inpainting.py", line 83, in __init__
    self.init_test()
  File "/home/b/MeInGame/uv_inpainting.py", line 268, in init_test
    self.reconstructor = Deep3DFace(self.sess, self.graph)
  File "/home/b/MeInGame/lib/deep3d.py", line 23, in __init__
    self.bfm = BFM_model('.', 'data/models/bfm2009_{}.mat'.format(bfm_version))
  File "/home/b/MeInGame/lib/deep3d.py", line 121, in __init__
    self.load_BFM09()
  File "/home/b/MeInGame/lib/deep3d.py", line 130, in load_BFM09
    self.shapeMU = model['meanshape'].astype(np.float32)  # mean face shape
KeyError: 'meanshape'

Help me please, how fix this problem?

**Comment by Laborant** [comment]
I fixed error message warnings.warn("Faces have invalid indices") via coment in string 69-70 in file obj_io.py

But remains one problem, how fix KeyError: 'meanshape'?

**Comment by hevinyu** [comment]
I had the same problem.
