### ISSUE TITLE
KeyError: 'meanshape'

### ISSUE THREAD

**Issue by gewenchao** [FuxiCV/MeInGame#27]
/home/gwc/anaconda3/envs/kehu1/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/gwc/anaconda3/envs/kehu1/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/gwc/anaconda3/envs/kehu1/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/gwc/anaconda3/envs/kehu1/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/gwc/anaconda3/envs/kehu1/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/gwc/anaconda3/envs/kehu1/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/gwc/anaconda3/envs/kehu1/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/gwc/anaconda3/envs/kehu1/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/gwc/anaconda3/envs/kehu1/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/gwc/anaconda3/envs/kehu1/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/gwc/anaconda3/envs/kehu1/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/gwc/anaconda3/envs/kehu1/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From /home/gwc/anaconda3/envs/kehu1/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:61: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
05-16 18:17:59 - x - INFO: - Namespace(adv_weight=0.01, batch_size=1, beta1=0.5, beta2=0.9, bfm_version='face', ckpt_interval=1000, con_weight=1, cpu=False, data_dir='./data/dataset/celeba_hq', data_gt_dir='./data/dataset/celeba_hq_gt', debug=False, epochs=400, face_model='230', gan_loss='nsgan', im_size=512, input='demo', l1_weight=3, learning_rate=0.0001, log_interval=10, mode='test', name='celeba_hq_demo', output=None, rename=False, restore=False, root_dir='.', sample_interval=1000, seed=1, start=0, std_weight=3, sty_weight=1, suffix='demo', sym_weight=0.1, use_cuda=True, uv_size=1024, workers=0)
Start testing...

2021-05-16 18:17:59.049588: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-05-16 18:17:59.053103: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3696000000 Hz
2021-05-16 18:17:59.053327: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x555ffe617880 executing computations on platform Host. Devices:
2021-05-16 18:17:59.053352: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2021-05-16 18:17:59.053726: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2021-05-16 18:17:59.053823: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-05-16 18:17:59.054057: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce GTX 1660 major: 7 minor: 5 memoryClockRate(GHz): 1.815
pciBusID: 0000:01:00.0
2021-05-16 18:17:59.054081: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2021-05-16 18:17:59.054132: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2021-05-16 18:17:59.054170: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2021-05-16 18:17:59.054204: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2021-05-16 18:17:59.054237: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2021-05-16 18:17:59.054269: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2021-05-16 18:17:59.056445: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2021-05-16 18:17:59.056457: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2021-05-16 18:17:59.103599: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-05-16 18:17:59.103617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2021-05-16 18:17:59.103621: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2021-05-16 18:17:59.104733: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-05-16 18:17:59.104963: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x555ffefc5e90 executing computations on platform CUDA. Devices:
2021-05-16 18:17:59.104972: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1660, Compute Capability 7.5
/home/gwc/anaconda3/envs/kehu1/lib/python3.7/site-packages/pytorch3d/io/obj_io.py:70: UserWarning: Faces have invalid indices
  warnings.warn("Faces have invalid indices")
Traceback (most recent call last):
  File "/home/MeInGame/main.py", line 180, in <module>
    main()
  File "/home/MeInGame/main.py", line 146, in main
    model = UVInpainting(config, device, sess, graph)
  File "/home/MeInGame/uv_inpainting.py", line 83, in __init__
    self.init_test()
  File "/home/MeInGame/uv_inpainting.py", line 268, in init_test
    self.reconstructor = Deep3DFace(self.sess, self.graph)
  File "/home/MeInGame/lib/deep3d.py", line 23, in __init__
    self.bfm = BFM_model('.', 'data/models/bfm2009_{}.mat'.format(bfm_version))
  File "/home/MeInGame/lib/deep3d.py", line 121, in __init__
    self.load_BFM09()
  File "/home/MeInGame/lib/deep3d.py", line 130, in load_BFM09
    self.shapeMU = model['meanshape'].astype(np.float32)  # mean face shape
KeyError: 'meanshape'

**Comment by wangruoyi1996** [comment]
Have you solved it? I have the same problem

**Comment by tpnam0901** [comment]
Any update on this error?

**Comment by wangruoyi1996** [comment]
The version of the model file is different from that of the code repository. In addition, I'm not very clear about the version of the dependent library. I have given up using MeInGame




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FuxiCV/MeInGame"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月12日(星期四) 上午10:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FuxiCV/MeInGame] KeyError: 'meanshape' (#27)





 
Any update on this error?

**Comment by tpnam0901** [comment]
Hi @wangruoyi1996, @gewenchao. I found the solution for this.
I took the wrong file for this "Deep3DFaceReconstruction/BFM/BFM_model_front.mat -> ./data/models/bfm2009_face.mat", the file I took was [BFM_front_idx.mat](https://github.com/microsoft/Deep3DFaceReconstruction/blob/master/BFM/BFM_front_idx.mat)
So I run the [Deep3DFaceReconstruction's](https://github.com/microsoft/Deep3DFaceReconstruction) demo.py to get "BFM_model_front.mat" and rename it to "bfm2009_face.mat". You can get the file [here](https://drive.google.com/file/d/1sB0FQyH_OA1gSQcrVDT0ncVWj36xAgvm/view?usp=sharing)
I had some errors with installing the [tf_mesh_renderer](https://github.com/google/tf_mesh_renderer) library but it is fixed by changing "googletest-master" to "googletest-main" in WORKSPACE file and add my virtual_env to path "export VIRTUAL_ENV=/home/usr/anaconda3/envs/deep3d".

**Comment by wangruoyi1996** [comment]
> Hi @wangruoyi1996, @gewenchao. I found the solution for this. I took the wrong file for this "Deep3DFaceReconstruction/BFM/BFM_model_front.mat -> ./data/models/bfm2009_face.mat", the file I took was [BFM_front_idx.mat](https://github.com/microsoft/Deep3DFaceReconstruction/blob/master/BFM/BFM_front_idx.mat) So I run the [Deep3DFaceReconstruction's](https://github.com/microsoft/Deep3DFaceReconstruction) demo.py to get "BFM_model_front.mat" and rename it to "bfm2009_face.mat". You can get the file [here](https://drive.google.com/file/d/1sB0FQyH_OA1gSQcrVDT0ncVWj36xAgvm/view?usp=sharing) I had some errors with installing the [tf_mesh_renderer](https://github.com/google/tf_mesh_renderer) library but it is fixed by changing "googletest-master" to "googletest-main" in WORKSPACE file and add my virtual_env to path "export VIRTUAL_ENV=/home/usr/anaconda3/envs/deep3d".

Thank you for your reply

**Comment by ChrisTiger93** [comment]
> Hi @wangruoyi1996, @gewenchao. I found the solution for this. I took the wrong file for this "Deep3DFaceReconstruction/BFM/BFM_model_front.mat -> ./data/models/bfm2009_face.mat", the file I took was [BFM_front_idx.mat](https://github.com/microsoft/Deep3DFaceReconstruction/blob/master/BFM/BFM_front_idx.mat) So I run the [Deep3DFaceReconstruction's](https://github.com/microsoft/Deep3DFaceReconstruction) demo.py to get "BFM_model_front.mat" and rename it to "bfm2009_face.mat". You can get the file [here](https://drive.google.com/file/d/1sB0FQyH_OA1gSQcrVDT0ncVWj36xAgvm/view?usp=sharing) I had some errors with installing the [tf_mesh_renderer](https://github.com/google/tf_mesh_renderer) library but it is fixed by changing "googletest-master" to "googletest-main" in WORKSPACE file and add my virtual_env to path "export VIRTUAL_ENV=/home/usr/anaconda3/envs/deep3d".

The final file link you share has been unaccessable, can you please share it again?
