### ISSUE TITLE
pytorch3d problem ！Help！

### ISSUE THREAD

**Issue by Kraken000** [FuxiCV/MeInGame#32]
/nvme/jiangyan/anaconda3/envs/MeInGame/lib/python3.7/site-packages/pytorch3d/io/obj_io.py:70: UserWarning: Faces have invalid indices
  warnings.warn("Faces have invalid indices")
Traceback (most recent call last):
  File "main.py", line 180, in <module>
    main()
  File "main.py", line 175, in main
    face_model=config.face_model)
  File "/nvme/jiangyan/MeInGame/uv_inpainting.py", line 363, in predict
    image, face_model)
  File "/nvme/jiangyan/MeInGame/uv_inpainting.py", line 331, in preprocess
    fragment = self.rasterizer(nsh_trans_mesh)
  File "/nvme/jiangyan/anaconda3/envs/MeInGame/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/nvme/jiangyan/anaconda3/envs/MeInGame/lib/python3.7/site-packages/pytorch3d/renderer/mesh/rasterizer.py", line 128, in forward
    cull_backfaces=raster_settings.cull_backfaces,
  File "/nvme/jiangyan/anaconda3/envs/MeInGame/lib/python3.7/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 145, in rasterize_meshes
    cull_backfaces,
  File "/nvme/jiangyan/anaconda3/envs/MeInGame/lib/python3.7/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 197, in forward
    cull_backfaces,
RuntimeError: Not compiled with GPU support (RasterizeMeshesNaive at /tmp/pip-req-build-9qdx_6q7/pytorch3d/csrc/rasterize_meshes/rasterize_meshes.h:112)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f186d1dc193 in /nvme/jiangyan/anaconda3/envs/MeInGame/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: RasterizeMeshesNaive(at::Tensor const&, at::Tensor const&, at::Tensor const&, int, float, int, bool, bool) + 0x16b (0x7f184a2fd7ab in /nvme/jiangyan/anaconda3/envs/MeInGame/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so)
frame #2: RasterizeMeshes(at::Tensor const&, at::Tensor const&, at::Tensor const&, int, float, int, int, int, bool, bool) + 0xed (0x7f184a2f4c3d in /nvme/jiangyan/anaconda3/envs/MeInGame/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x2d87d (0x7f184a30d87d in /nvme/jiangyan/anaconda3/envs/MeInGame/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x2d95e (0x7f184a30d95e in /nvme/jiangyan/anaconda3/envs/MeInGame/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x27a10 (0x7f184a307a10 in /nvme/jiangyan/anaconda3/envs/MeInGame/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so)
<omitting python frames>
frame #11: THPFunction_apply(_object*, _object*) + 0xa7f (0x7f186dc9614f in /nvme/jiangyan/anaconda3/envs/MeInGame/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #47: __libc_start_main + 0xf0 (0x7f1871fe9840 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by Kraken000** [comment]
解决了解决了，安装pytorch3d的时候，因为系统环境变量里没有指定CUDA_HOME的地址，所以安装的时候找不到CUDA，虽然安装上了pytorch3d没有报错，但是没有支持CUDA。需要在pytorch3d的源码里手动指定一下CUDA_HOME的地址参数，再重新安装编译一下就好了。
